name: 'GitHub Actions Approval Request'
description: 'Request an approval to trigger a GitHub Action'
inputs:
  trigger-workflow:
    description: 'ID of Workflow to trigger for the repository'
    required: true
  notification-webhook-url:
    description: 'Webhook URL to notify'
    required: true
  github-actions-approval-api-url:
    description: 'Base URL for github-actions-approval-api'
    required: true
runs:
  using: 'node16'
  main: 'index.js'
